name: Publish container image

on:
  push:
    branches: "**"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  docker:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0

      # Outputs the name of the repository (owner/repo)
      - name: Get image name
        id: image
        run: |
          IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "image_name=ghcr.io/${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Prepare Release Tags
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          # Remove everything else than the tagged version
          VERSION=${GITHUB_REF#refs/tags/}
          echo "
          VERSION=$VERSION
          TAGS=${{ steps.image.outputs.image_name }}:${VERSION}
          " >> "${GITHUB_ENV}"

      - name: Prepare Branch Tags
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        run: |
          # Version name is the branch name
          # Slashes are substituted by dashes
          CLEAN_BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)
          TAGS=$"\
          ghcr.io/${{ steps.image.outputs.image_name }}:${CLEAN_BRANCH_NAME}}
          "
          # Set version name for open-containers version label as:
          # <branch>-<drift>-g<6-digit-hash>
          VERSION=$(git describe --all --long | tr -d $'\n')
          # Output the target tags
          echo "
          TAGS=${TAGS}
          VERSION=${VERSION}
          " >> "${GITHUB_ENV}"

      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18  # v2.1.0
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@15c905b16b06416d2086efa066dd8e3a35cc7f98  # v2.4.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a  # v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671  # v4.0.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ env.TAGS }}
          build-args: |
            COMMIT_ID=${{ github.sha }}
            VERSION=${{ env.VERSION }}

      - name: Output image digest
        run: |
          echo $"\
            Digest: ${{ steps.docker_build.outputs.digest }}
            Tags: ${{ env.TAGS }}"
